import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import MainFooter from "@/app/components/MainFooter";
import MainHeader from "@/app/components/MainHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className=" bg-black text-white">
        <Theme
          accentColor="blue"
          grayColor="slate"
          appearance="dark"
          className="flex flex-col h-full flex-column"
        >
          <MainHeader />
          {children}
          <MainFooter />
        </Theme>
      </body>
    </html>
  );
}
